### ISSUE TITLE
build.sh not working 

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp-Portable#37]
```
macellan@fedora:~/core$ ./build.sh
Building redirector...
./build.sh: satır 4: go: komut yok
```
translated:
```
macellan@fedora:~/core$ ./build.sh
Building redirector...
./build.sh: line 4: go: no command
```

**Comment by universish** [comment]
```
macellan@fedora:~/core$ ls
build.bat              fileInUse_linux.go    LICENSE       README_ja.md
build.sh               fileInUse_windows.go  main.go       README.md
config                 floorp_downloader     patcher_src   tools.go
CREDITS.txt            floorp.ico            patches       utils
fatalerror_linux.go    go.mod                patches.json  versioninfo.json
fatalerror_windows.go  go.sum                pathUtils.go

```

```
macellan@fedora:~$ uname -a
Linux fedora 6.11.4-201.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:04:22 UTC 2024 x86_64 GNU/Linux
```

```
macellan@fedora:~$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

```
macellan@fedora:~$ lsb_release -a
shell-init: geçerli dizin alınırken hata: getcwd: üst dizinlere erişilemiyor: Böyle bir dosya ya da dizin yok
LSB Version:	:core-5.0-amd64:core-5.0-noarch
Distributor ID:	Fedora
Description:	Fedora release 40 (Forty)
Release:	40
Codename:	Forty
```

```
macellan@fedora:~$ echo $DISPLAY
:0
```
```
macellan@fedora:~$ loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=wayland
```
```
macellan@fedora:~$ ps -e | grep -E 'Xwayland|Xorg'
  14242 ?        00:00:00 Xwayland
```
```
macellan@fedora:~$ echo $XDG_SESSION_TYPE
wayland
```
```
macellan@fedora:~$ echo $XDG_CURRENT_DESKTOP
GNOME
```
```
macellan@fedora:~$ echo $DESKTOP_SESSION
gnome
```

**Comment by creeper-0910** [comment]
Build procedures are not supported.

**Comment by universish** [comment]
```
macellan@fedora:~/core$ go version
bash: go: command not found...
Packages containing this file:
'gcc-go'
'golang-bin'
```

`sudo dnf install golang`

```
Established:
  go-filesystem-3.5.0-1.fc40.x86_64     golang-1.22.7-1.fc40.x86_64            
  golang-bin-1.22.7-1.fc40.x86_64       golang-src-1.22.7-1.fc40.noarch        
  mercurial-6.7.4-3.fc40.x86_64         python3-fb-re2-1.0.7-15.fc40.x86_64    

Done!
```

```
macellan@fedora:~/core$ go version
go version go1.22.7 linux/amd64
```
```
macellan@fedora:~/core$ ./build.sh
Building redirector...
Building patcher...
```
```
macellan@fedora:~/core$ ./floorp
2024/10/28 01:51:30 bwrap: execvp /home/macellan/core/core/floorp: No such file or directory

panic: exit status 1

goroutine 1 [running]:
main.main()
	/home/macellan/core/main.go:165 +0x10d2
```
`macellan@fedora:~/core$ chmod +x floorp`
```
macellan@fedora:~/core$ ./floorp
2024/10/28 01:51:55 bwrap: execvp /home/macellan/core/core/floorp: No such file or directory

panic: exit status 1

goroutine 1 [running]:
main.main()
	/home/macellan/core/main.go:165 +0x10d2
```
![Ekran Görüntüsü - 2024-10-28 01-52-24](https://github.com/user-attachments/assets/7007d10b-92a2-40f3-bfc3-6dd50edd1a08)

**Comment by universish** [comment]
There is no information in the README about installing the go package.

**Comment by universish** [comment]
@creeper-0910 
I changed the title. the problem is a different problem. can you please open the issue?
Also help me please. why i got this error. this is not build issue. i managed to build. 
problem: the portable version of floorp is not working.

**Comment by typeling1578** [comment]
If you choose to build it yourself, here is a reference: https://github.com/Floorp-Projects/Floorp-Portable/blob/ESR128/.github/workflows/build.yml

You may also create a PR for documentation purposes.

**Comment by universish** [comment]
Hello. I'm not a programmer. I'm not a coder. I don't know how to create a PR.

**Comment by universish** [comment]
@creeper-0910
I changed the title. the problem is a different problem. can you please open the issue?
Also help me please. why i got this error. this is not build issue. i managed to build.
problem: the portable version of floorp is not working.
