### ISSUE TITLE
Floorp-Portable version of floorp is not working

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp-Portable#38]
```
macellan@fedora:~/core$ ./floorp
2024/10/28 01:51:30 bwrap: execvp /home/macellan/core/core/floorp: No such file or directory

panic: exit status 1

goroutine 1 [running]:
main.main()
	/home/macellan/core/main.go:165 +0x10d2
```
```
macellan@fedora:~/core$ chmod +x floorp
```
```
macellan@fedora:~/core$ ./floorp
2024/10/28 01:51:55 bwrap: execvp /home/macellan/core/core/floorp: No such file or directory

panic: exit status 1

goroutine 1 [running]:
main.main()
	/home/macellan/core/main.go:165 +0x10d2
```

does not work
![380537112-7007d10b-92a2-40f3-bfc3-6dd50edd1a08](https://github.com/user-attachments/assets/8ddc72ee-b74a-4eff-917d-40b3feba1134)

**Comment by universish** [comment]
my platform is fedora 40
